name: Xentaria.de
version: 0.1
author: stonie1901
website: http://www.xentaria.de/
main: de.xentaria.core.Main
depend: [Vault]

commands:
  cc:
    description: Loescht den Chat
  reload:
    description: Reloaded den Server
  heal:
    description: Gibt dem Spieler volles Leben
    permission: xentaria.heal
    usage: /<command> [Spieler]
  sun:
    description: Aendert das Wetter
    permission: xentaria.weather
    usage: /<command>
    aliases: [rain,storm]
  speed:
    description: Setzt deine Geschwindigkeit
    permission: xentaria.speed
    usage: /<command> [1-10]
  fly:
    description: aedert deinen Flugmodus
    usage: /<command> [1-10]
  farmen:
    description: Teleportiert dich zur Farmwelt
    usage: /<command>
  ip:
    description: IP-Befehl
    usage: /<command>
  teleport:
    description: Teleportiert dich zu einem Spieler
    usage: /<command> [Spieler1] [Spieler2]
    aliases: [tp]